# Generated by Django 4.2.25 on 2025-11-03 00:38

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('attachment_type', models.CharField(choices=[('cv_resume', 'CV/Resume'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio')], default='cv_resume', max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{2}[A-Z0-9]{4}[0-9]{7}([A-Z0-9]?){0,16}$', 'Enter a valid IBAN.')])),
            ],
            options={
                'db_table': 'bank_info',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='course_certificates/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_degree', models.CharField(blank=True, choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=20)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('grad_year', models.PositiveIntegerField(blank=True, null=True)),
                ('certificates', models.FileField(blank=True, null=True, upload_to='education_certificates/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tasks', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='experience_certificates/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('proficiency_level', models.CharField(choices=[('Basic', 'Basic'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], max_length=20)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=128)),
                ('father_name', models.CharField(max_length=128)),
                ('grand_name', models.CharField(max_length=128)),
                ('family_name', models.CharField(max_length=128)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('id_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Personal Info',
                'db_table': 'personal_info',
            },
        ),
        migrations.CreateModel(
            name='ProfileCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('personal_info_complete', models.BooleanField(default=False)),
                ('education_complete', models.BooleanField(default=False)),
                ('experience_complete', models.BooleanField(default=False)),
                ('skills_complete', models.BooleanField(default=False)),
                ('bank_info_complete', models.BooleanField(default=False)),
                ('attachments_complete', models.BooleanField(default=False)),
                ('overall_completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile_completion',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('skill_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='WorkPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('has_seasonal_experience', models.BooleanField(default=False)),
                ('can_work_weekends', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'work_preferences',
            },
        ),
    ]
