# Generated by Django 5.2.8 on 2025-11-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number', max_length=50),
        ),
    ]
