# Generated by Django 5.2.8 on 2025-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_family_name_user_father_name_user_grand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sign_up_source',
            field=models.CharField(choices=[('organic', 'Organic'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('job_portal', 'Job Portal'), ('advertisement', 'Advertisement'), ('web_app', 'Web App')], default='organic', max_length=30),
        ),
    ]
